### ISSUE TITLE
Is there any way to get back my deleted files?

### ISSUE THREAD

**Issue by muratcansimsek** [TERRAOperative/OneDrive-Uninstaller#8]
I lost all my files because of some stupid forum user. I looked at OneDrive, but my text files on the desktop are completely missing. Is there really a way I can bring it back? I tried a software called Recuva but it didn't work.

**Comment by n0f4c3** [comment]
My question might seem strange, but have you checked if your files might be in the OneDrive trash bin?

To access the OneDrive trash bin, you can follow these steps:

1. Log into your Microsoft account 
2. Click on the OneDrive icon
3. The Recycle Bin is on the left side of your OneDrive page.

For OneDrive for business, 

1. Click on the settings button, 
2. Navigate to "site Settings"
3. under site collection administration, you will see the "recycle Bin"

**Comment by muratcansimsek** [comment]
Yes, checked. All gone.

**Comment by n0f4c3** [comment]
The only option left for you is to contact OneDrive support. They might be able to do something, but it’s not guaranteed. In this article , you will find a link that says ‘email the OneDrive support team’. You must be logged into your OneDrive account for the email link to work and display the contact window.  https://support.microsoft.com/en-us/office/find-lost-or-missing-files-in-onedrive-0d929e0d-8682-4295-982b-4bd75a3daa01#bkmk_stillcantfind 

In this article, you will also find instructions on what you need to provide them so they can help you.

**Comment by superjmiscool** [comment]
hi
I had the same problem, before uninstalling onedrive, the address of the desktop was tampered with by onedrive to users/onedrive/desktop/, unfortunately I didn't notice the change (did anyone think of it in advance?). Unfortunately, I didn't notice this change (who thought of it in advance?), and since I hadn't used onedrive for a long time before I uninstalled it, unfortunately some of the desktop files were in the users/onedrive/desktop/ path, which led to the deletion of the desktop contents when I uninstalled the software with [OneDrive Uninstaller v1.4.bat]. And I can't recover from onedrive recycle bin, is there any remedy for this, currently known data recovery software, disk dill and Windows File Recovery can't recover my lost files from desktop! @n0f4c3
